plugins {
    id 'java'
}

dependencies {
    testImplementation project(':compiler-core')
    testImplementation project(':compiler-blueprint')
    testImplementation project(':compiler-contracts')
    testImplementation project(':compiler-workflow')
    testImplementation project(':compiler-projection')
    testImplementation project(':compiler-generator')
    implementation project(':compiler-dsl')    
    // Testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.3'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.3'
    
    // For EndToEndDbpkgTest
    testImplementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
