package org.devinebyte.sdk.plugin;

/**
 * Compiler lifecycle events.
 */
public enum EventType {

    COMPILATION_STARTED,

    LEXING_STARTED,
    LEXING_COMPLETED,

    PARSING_STARTED,
    PARSING_COMPLETED,

    VALIDATION_STARTED,
    VALIDATION_COMPLETED,

    BLUEPRINT_STARTED,
    BLUEPRINT_COMPLETED,

    GENERATION_STARTED,
    GENERATION_COMPLETED,

    COMPILATION_COMPLETED,

    ERROR_OCCURRED
}
