plugins {
    id 'java'
    id 'application'
}

dependencies {
    implementation project(':runtime-core')
    implementation project(':runtime-module')
    implementation project(':runtime-config')
    implementation project(':runtime-bootstrap')
    implementation project(':runtime-tenant')
    implementation project(':runtime-event')
    implementation project(':runtime-workflow')
    implementation project(':runtime-projection')
    implementation project(':compiler-workflow')
    implementation project(':compiler-projection')   

    implementation 'com.google.inject:guice:5.1.0' // ADD THIS for Guice.createInjector
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.15.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2'
    implementation 'jakarta.inject:jakarta.inject-api:2.0.1'
}

application {
    mainClass = 'io.devinebyte.runtime.Main'
}
