plugins {
    id 'java'
    id 'application'
}

group = 'io.devinebyte.compiler'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

application {
    mainClass = 'io.devinebyte.compiler.cli.CompilerCli'
    applicationName = 'devinebyte'
}

// ADD THIS
run {
    args 'compile', '-d', 'acme.dbdsl', '-t', 'acme', '-v', '1.0.0', '-o', 'build/output'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':compiler-core')
    implementation project(':compiler-audit')
    implementation project(':runtime-config')
    implementation project(':compiler-packaging')
    implementation project(':compiler-dsl')
    implementation project(':compiler-blueprint')
    implementation project(':compiler-optimizer')
    implementation project(':compiler-contracts')
    implementation project(':compiler-workflow')
    implementation project(':compiler-projection')
    implementation project(':compiler-generator')
    implementation project(':compiler-sdk')

    implementation 'info.picocli:picocli:4.7.6'
    implementation 'io.micronaut:micronaut-inject:4.5.0'
    implementation 'io.micronaut:micronaut-runtime:4.5.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'

    compileOnly 'jakarta.inject:jakarta.inject-api:2.0.1'
    annotationProcessor 'io.micronaut:micronaut-inject-java:4.5.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
